name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.18.0
      uses: actions/setup-node@v4
      with:
        node-version: '18.18.0'  # Đặt phiên bản cụ thể là 18.18.0
        cache: 'npm'
    - run: npm ci
    - run: npm test
